'''
You are given two strings, s and t which only consist of lowercase letters. 
t is generated by shuffling the letters in s as well as potentially adding an additional random character. 
Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''

'''

def spot_difference(s , t):
    '''
    To spot the difference, I use a set to hold the common words.
    Now, because the words that are common are common, I am fine with using a set 
    and ignoring repetitive characters. 
    A character that is different will not be part of our set.
    '''
    s_hash = set() 
    for char in s:
        s_hash.add(char) 
    for char in t:
        if char not in s_hash:
            return char  
    return ''

if __name__ == "__main__":
   s = "coding"
   t = "ingcod"
   test=spot_difference(s , t)
   print(test)
